# Analise Exploratória de Dados - Hospitais e Leitos 2007 - 2022

Essa ánalise exploratória tem como interesse analisar os dados de Hospitais e Leitos de maneira livre, sem ter perguntas prévias a serem respondidas. Para isso, utilizaremos dados disponibilizados pelo site federal https://dados.gov.br/ .

<b>Descrição, do Conjunto de Dados, fornecida pelo site:</b>
<br><i>Disponibilização de dados gerais dos estabelecimentos hospitalares, leitos gerais e complementares, bem como informações de contato com os estabelecimentos como endereço, telefone e e-mail.
<br>
<i>As bases de dados das informações são disponibilizadas por competência mensal e anual. Neste sentido, poderão ser baixados os arquivos. Esta medida permite a cessão de dados contidos nas bases nacionais dos sistemas de informação em saúde (que é o caso do TABWIN) e, portanto, cabe o atendimento à Lei de Acesso à Informação e Lei Geral de Proteção de Dados, por isso os dados serão disponibilizados com sigilo da informação pessoal, não sendo permitido o rastreio ou identificação de qualquer cidadão por meio de banco de dados agregados.
<br>
<i>Limitações referentes ao conteúdo podem ocorrer em razão da forma de captura de dados (dados enviados pelos gestores locais de saúde). A atualização de dados ocorrerá por competência mensal”
<br>
<br>
    <b>Link: https://dados.gov.br/dados/conjuntos-dados/hospitais-e-leitos

### Dicionário de Dados:

TODO
inserir dicionario de dados
https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/Leitos_SUS/Dicion%C3%A1rio_Leito_hospitalar.pdf

### Carregando os dados

In [61]:
# Importando bibliotecas
import pandas as pd
import plotly.express as px
import plotly.figure_factory as ff

# Biblioteca com os modulos do sistema operacional (sera utilizado para facilitar a leitura dos arquivos)
import os

print("Bibliotecas carregadas!")

Bibliotecas carregadas!


In [62]:
# Lista dos arquivos dentro da pasta "Database"
files = os.listdir("Database")

df_list = []

# Leitura de cada arquivo da lista criada anteriormente
for file in files:
    df_list.append(pd.read_csv("Database/" + file, on_bad_lines="skip"))

# Junta os DataFrames lidos em um único DataFrame
df_final = pd.concat(df_list)

In [63]:
df_final

COMP    REGIAO  UF                MUNICIPIO  MOTIVO DESABILITACAO  \
0      200707.0  NORDESTE  PE  CABO DE SANTO AGOSTINHO                   NaN   
1      200708.0  NORDESTE  PE  CABO DE SANTO AGOSTINHO                   NaN   
2      200709.0  NORDESTE  PE  CABO DE SANTO AGOSTINHO                   NaN   
3      200710.0  NORDESTE  PE  CABO DE SANTO AGOSTINHO                   NaN   
4      200711.0  NORDESTE  PE  CABO DE SANTO AGOSTINHO                   NaN   
...         ...       ...  ..                      ...                   ...   
85308  202208.0  NORDESTE  MA                BACABEIRA                   NaN   
85309  202209.0  NORDESTE  MA                BACABEIRA                   NaN   
85310  202210.0  NORDESTE  MA                BACABEIRA                   NaN   
85311  202211.0  NORDESTE  MA                BACABEIRA                   NaN   
85312  202212.0  NORDESTE  MA                BACABEIRA                   NaN   

            CNES                  NOME ESTABELECIMENTO  \
0           27.0            CASA DE SAUDE SANTA HELENA   
1           27.0            CASA DE SAUDE SANTA HELENA   
2           27.0            CASA DE SAUDE SANTA HELENA   
3           27.0            CASA DE SAUDE SANTA HELENA   
4           27.0            CASA DE SAUDE SANTA HELENA   
...          ...                                   ...   
85308  9997784.0  HOSPITAL E MATERNIDADE NAILA GONCALO   
85309  9997784.0  HOSPITAL E MATERNIDADE NAILA GONCALO   
85310  9997784.0  HOSPITAL E MATERNIDADE NAILA GONCALO   
85311  9997784.0  HOSPITAL E MATERNIDADE NAILA GONCALO   
85312  9997784.0  HOSPITAL E MATERNIDADE NAILA GONCALO   

                                         RAZAO SOCIAL TP_GESTAO  \
0      CASA DE SAUDE  E MATERNIDADE SANTA HELENA LTDA         M   
1       CASA DE SAUDE E MATERNIDADE SANTA HELENA LTDA         M   
2       CASA DE SAUDE E MATERNIDADE SANTA HELENA LTDA         M   
3       CASA DE SAUDE E MATERNIDADE SANTA HELENA LTDA         M   
4       CASA DE SAUDE E MATERNIDADE SANTA HELENA LTDA         M   
...                                               ...       ...   
85308                         MUNICIPIO DE BACABAEIRA         M   
85309                         MUNICIPIO DE BACABAEIRA         M   
85310                         MUNICIPIO DE BACABAEIRA         M   
85311                         MUNICIPIO DE BACABAEIRA         M   
85312                         MUNICIPIO DE BACABAEIRA         M   

       CO_TIPO_UNIDADE  ... UTI ADULTO - SUS  UTI PEDIATRICO - EXIST  \
0                  5.0  ...              0.0                     0.0   
1                  5.0  ...              0.0                     0.0   
2                  5.0  ...              0.0                     0.0   
3                  5.0  ...              0.0                     0.0   
4                  5.0  ...              0.0                     0.0   
...                ...  ...              ...                     ...   
85308              5.0  ...              0.0                     0.0   
85309              5.0  ...              0.0                     0.0   
85310              5.0  ...              0.0                     0.0   
85311              5.0  ...              0.0                     0.0   
85312              5.0  ...              0.0                     0.0   

      UTI PEDIATRICO - SUS UTI NEONATAL - EXIST UTI NEONATAL - SUS  \
0                      0.0                  0.0                0.0   
1                      0.0                  0.0                0.0   
2                      0.0                  0.0                0.0   
3                      0.0                  0.0                0.0   
4                      0.0                  0.0                0.0   
...                    ...                  ...                ...   
85308                  0.0                  0.0                0.0   
85309                  0.0                  0.0                0.0   
85310                  0.0                  0.0      

## Visão Geral do Dataset e Tratamento dos Dados

In [64]:
print("Esse dataset possui {} linhas e {} colunas!".format(df_final.shape[0],df_final.shape[1]))

Esse dataset possui 1244339 linhas e 35 colunas!


Para melhor entendermos esse dataset, iremos olhar para as primeiras e as ultimas 5 linhas dele. Para isso iremos transpo-lo, para que possamos observar melhor seus valores ao longo das colunas.

In [65]:
# 5 primeiros valores
df_final.head(5).T

0  \
COMP                                                                   200707.0   
REGIAO                                                                 NORDESTE   
UF                                                                           PE   
MUNICIPIO                                               CABO DE SANTO AGOSTINHO   
MOTIVO DESABILITACAO                                                        NaN   
CNES                                                                       27.0   
NOME ESTABELECIMENTO                                 CASA DE SAUDE SANTA HELENA   
RAZAO SOCIAL                     CASA DE SAUDE  E MATERNIDADE SANTA HELENA LTDA   
TP_GESTAO                                                                     M   
CO_TIPO_UNIDADE                                                             5.0   
DS_TIPO_UNIDADE                                                  HOSPITAL GERAL   
NATUREZA_JURIDICA                                                        2000.0   
DESC_NATUREZA_JURIDICA                                         HOSPITAL_PRIVADO   
NO_LOGRADOURO                                     AVN PRESIDENTE GETULIO VARGAS   
NU_ENDERECO                                                                 428   
NO_COMPLEMENTO                                                              NaN   
NO_BAIRRO                                                                CENTRO   
CO_CEP                                                               54505560.0   
NU_TELEFONE                                                        (81)35210355   
NO_EMAIL                                                                    NaN   
LEITOS EXISTENTE                                                           67.0   
LEITOS SUS                                                                 21.0   
UTI TOTAL - EXIST                                                           0.0   
UTI TOTAL - SUS                                                             0.0   
UTI ADULTO - EXIST                                                          0.0   
UTI ADULTO - SUS                                                            0.0   
UTI PEDIATRICO - EXIST                                                      0.0   
UTI PEDIATRICO - SUS                                                        0.0   
UTI NEONATAL - EXIST                                                        0.0   
UTI NEONATAL - SUS                                                          0.0   
UTI QUEIMADO - EXIST                                                        0.0   
UTI QUEIMADO - SUS                                                          0.0   
UTI CORONARIANA - EXIST                                                     0.0   
UTI CORONARIANA - SUS                                                       0.0   
REM INSERTING into EXPORT_TABLE                                             NaN   

                                                                             1  \
COMP                                                                  200708.0   
REGIAO                                                                NORDESTE   
UF                                                                          PE   
MUNICIPIO                                              CABO DE SANTO AGOSTINHO   
MOTIVO DESABILITACAO                                                       NaN   
CNES                                                                      27.0   
NOME ESTABELECIMENTO                                CASA DE SAUDE SANTA HELENA   
RAZAO SOCIAL                     CASA DE SAUDE E MATERNIDADE SANTA HELENA LTDA   
TP_GESTAO                                                                    M   
CO_TIPO_UNIDADE                                                            5.0   
DS_TIPO_UNIDADE                                                 HOSPITAL GERAL   
NATUREZA_JURIDICA                                                       2000.0   
DESC_NATUREZA_JURIDICA 

In [66]:
# 5 ultimos valores
df_final.tail(5).T

85308  \
COMP                                                         202208.0   
REGIAO                                                       NORDESTE   
UF                                                                 MA   
MUNICIPIO                                                   BACABEIRA   
MOTIVO DESABILITACAO                                              NaN   
CNES                                                        9997784.0   
NOME ESTABELECIMENTO             HOSPITAL E MATERNIDADE NAILA GONCALO   
RAZAO SOCIAL                                  MUNICIPIO DE BACABAEIRA   
TP_GESTAO                                                           M   
CO_TIPO_UNIDADE                                                   5.0   
DS_TIPO_UNIDADE                                        HOSPITAL GERAL   
NATUREZA_JURIDICA                                              1244.0   
DESC_NATUREZA_JURIDICA                               HOSPITAL_PUBLICO   
NO_LOGRADOURO                                  RUA HUMBERTO DE CAMPOS   
NU_ENDERECO                                                       S/N   
NO_COMPLEMENTO                                                    NaN   
NO_BAIRRO                                                      CENTRO   
CO_CEP                                                     65143000.0   
NU_TELEFONE                                                       NaN   
NO_EMAIL                                                          NaN   
LEITOS EXISTENTE                                                 26.0   
LEITOS SUS                                                       26.0   
UTI TOTAL - EXIST                                                 0.0   
UTI TOTAL - SUS                                                   0.0   
UTI ADULTO - EXIST                                                0.0   
UTI ADULTO - SUS                                                  0.0   
UTI PEDIATRICO - EXIST                                            0.0   
UTI PEDIATRICO - SUS                                              0.0   
UTI NEONATAL - EXIST                                              0.0   
UTI NEONATAL - SUS                                                0.0   
UTI QUEIMADO - EXIST                                              0.0   
UTI QUEIMADO - SUS                                                0.0   
UTI CORONARIANA - EXIST                                           0.0   
UTI CORONARIANA - SUS                                             0.0   
REM INSERTING into EXPORT_TABLE                                   NaN   

                                                                85309  \
COMP                                                         202209.0   
REGIAO                                                       NORDESTE   
UF                                                                 MA   
MUNICIPIO                                                   BACABEIRA   
MOTIVO DESABILITACAO                                              NaN   
CNES                                                        9997784.0   
NOME ESTABELECIMENTO             HOSPITAL E MATERNIDADE NAILA GONCALO   
RAZAO SOCIAL                                  MUNICIPIO DE BACABAEIRA   
TP_GESTAO                                                           M   
CO_TIPO_UNIDADE                                                   5.0   
DS_TIPO_UNIDADE                                        HOSPITAL GERAL   
NATUREZA_JURIDICA                                              1244.0   
DESC_NATUREZA_JURIDICA                               HOSPITAL_PUBLICO   
NO_LOGRADOURO                                  RUA HUMBERTO DE CAMPOS   
NU_ENDERECO                                                       S/N   
NO_COMPLEMENTO                                                    NaN   
NO_BAIRRO                                                      CENTRO   
CO_CEP                                                     65143000.0   
NU_TELEFONE                                     

### Tipos de dados

In [67]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1244339 entries, 0 to 85312
Data columns (total 35 columns):
 #   Column                           Non-Null Count    Dtype  
---  ------                           --------------    -----  
 0   COMP                             1244338 non-null  float64
 1   REGIAO                           1244338 non-null  object 
 2   UF                               1244338 non-null  object 
 3   MUNICIPIO                        1244338 non-null  object 
 4   MOTIVO DESABILITACAO             0 non-null        float64
 5   CNES                             1244338 non-null  float64
 6   NOME ESTABELECIMENTO             1244338 non-null  object 
 7   RAZAO SOCIAL                     1244338 non-null  object 
 8   TP_GESTAO                        1244338 non-null  object 
 9   CO_TIPO_UNIDADE                  1244338 non-null  float64
 10  DS_TIPO_UNIDADE                  1244338 non-null  object 
 11  NATUREZA_JURIDICA                1244338 non-null  f

Há apenas dois tipos de dados salvos nas colunas: float64 - númerico; object - categorico. Mais especificadamente 20 colunas numericas e 15 colunas categóricas.

### Estatisticas Gerais

In [68]:
# Estatisticas gerais do Dataframe, arredondando para 2 casas decimais os valores mostrados
df_final.describe().round(2)

COMP  MOTIVO DESABILITACAO        CNES  CO_TIPO_UNIDADE  \
count  1244338.00                   0.0  1244338.00       1244338.00   
mean    201448.77                   NaN  2962187.13             6.64   
std        455.86                   NaN  1599078.52             3.60   
min     200707.00                   NaN       27.00             5.00   
25%     201101.00                   NaN  2270021.00             5.00   
50%     201407.00                   NaN  2515504.00             5.00   
75%     201904.00                   NaN  2801922.00             7.00   
max     202212.00                   NaN  9997784.00            21.00   

       NATUREZA_JURIDICA       CO_CEP  LEITOS EXISTENTE  LEITOS SUS  \
count         1244338.00   1244338.00        1244338.00  1244285.00   
mean             2056.03  54169740.01             69.44       48.51   
std              1038.10  25570925.27             92.55       80.00   
min              1000.00   1023010.00              1.00        0.00   
25%              1031.00  35570000.00             20.00        5.00   
50%              2000.00  58805250.00             40.00       26.00   
75%              3000.00  75370000.00             81.00       55.00   
max              4014.00  99980000.00           2220.00     1730.00   

       UTI TOTAL - EXIST  UTI TOTAL - SUS  UTI ADULTO - EXIST  \
count         1244338.00       1244338.00          1244338.00   
mean                5.40             2.62                3.59   
std                14.06             9.59                9.74   
min                 0.00             0.00                0.00   
25%                 0.00             0.00                0.00   
50%                 0.00             0.00                0.00   
75%                 4.00             0.00                0.00   
max               434.00           325.00              256.00   

       UTI ADULTO - SUS  UTI PEDIATRICO - EXIST  UTI PEDIATRICO - SUS  \
count        1244338.00              1244338.00            1244338.00   
mean               1.71                    0.59                  0.31   
std                6.43                    2.63                  1.85   
min                0.00                    0.00                  0.00   
25%                0.00                    0.00                  0.00   
50%                0.00                    0.00                  0.00   
75%                0.00                    0.00                  0.00   
max              245.00                  102.00                 51.00   

       UTI NEONATAL - EXIST  UTI NEONATAL - SUS  UTI QUEIMADO - EXIST  \
count            1244338.00          1244338.00            1244338.00   
mean                   1.12                0.56                  0.03   
std                    4.29                2.91                  0.49   
min                    0.00                0.00                  0.00   
25%                    0.00                0.00                  0.00   
50%                    0.00                0.00                  0.00   
75%                    0.00                0.00                  0.00   
max                  124.00              104.00                 28.00   

       UTI QUEIMADO - SUS  UTI CORONARIANA - EXIST  UTI CORONARIANA - SUS  
count          1244338.00               1244338.00             1244338.00  
mean                 0.02                     0.07                   0.02  
std                  0.35                     1.02                   0.46  
min                  0.00                     0.00                   0.00  
25%                  0.00                     0.00                   0.00  
50%                  0.00                     0.00                   0.00  
75%                  0.00                     0.00                   0.00  
max                 28.00                    66.00                  28.00

Apesar de possuirmos 20 colunas identificadas como numericas, algumas possuem dados a serem considerados como categoricos. Como é o caso das colunas: "COMP", "CNES", "CO_TIPO_UNIDADE", "NATUREZA_JURIDICA" e "CO_CEP".

### Valores Nulos

In [69]:
# Soma dos valores nulos de cada coluna do DataFrame
df_final.isna().sum()

COMP                                     1
REGIAO                                   1
UF                                       1
MUNICIPIO                                1
MOTIVO DESABILITACAO               1244339
CNES                                     1
NOME ESTABELECIMENTO                     1
RAZAO SOCIAL                             1
TP_GESTAO                                1
CO_TIPO_UNIDADE                          1
DS_TIPO_UNIDADE                          1
NATUREZA_JURIDICA                        1
DESC_NATUREZA_JURIDICA                  48
NO_LOGRADOURO                            1
NU_ENDERECO                            329
NO_COMPLEMENTO                     1054771
NO_BAIRRO                                4
CO_CEP                                   1
NU_TELEFONE                          77799
NO_EMAIL                            518001
LEITOS EXISTENTE                         1
LEITOS SUS                              54
UTI TOTAL - EXIST                        1
UTI TOTAL -

Para ter uma visão mais clara sobre essas quantidades, iremos observar as porcentagens de valores nulos para cada coluna.

In [70]:
(df_final.isnull().mean() * 100).round(2)

COMP                                 0.00
REGIAO                               0.00
UF                                   0.00
MUNICIPIO                            0.00
MOTIVO DESABILITACAO               100.00
CNES                                 0.00
NOME ESTABELECIMENTO                 0.00
RAZAO SOCIAL                         0.00
TP_GESTAO                            0.00
CO_TIPO_UNIDADE                      0.00
DS_TIPO_UNIDADE                      0.00
NATUREZA_JURIDICA                    0.00
DESC_NATUREZA_JURIDICA               0.00
NO_LOGRADOURO                        0.00
NU_ENDERECO                          0.03
NO_COMPLEMENTO                      84.77
NO_BAIRRO                            0.00
CO_CEP                               0.00
NU_TELEFONE                          6.25
NO_EMAIL                            41.63
LEITOS EXISTENTE                     0.00
LEITOS SUS                           0.00
UTI TOTAL - EXIST                    0.00
UTI TOTAL - SUS                   

Analisando os valores nulos apresentados para cada coluna, há pelo menos uma linha em cada (possivelmente a mesma) coluna, com um valor nulo. Além disso há colunas com grandes porcentagens de valores nulos, o caso das colunas: "MOTIVO DESABILITACAO", "NO_COMPLEMENTO", "NO_EMAIL", "NO_EMAIL","REM INSERTING into EXPORT_TABLE".

Visto que as colunas "REM INSERTING into EXPORT_TABLE" e "MOTIVO DESABILITACAO" possuem apenas valores nulos, sendo a primeira provavelmente resultante de algum "bug" durante a extração. Iremos retira-las do Dataframe.

In [71]:
# Deletando colunas atribuidas ao DataFrame com 100% de valores nulos
df_final.drop(["MOTIVO DESABILITACAO","REM INSERTING into EXPORT_TABLE"], axis=1, inplace=True)

In [75]:
# Selecionando linha da coluna "COMP" com valores nulos
df_final[df_final["COMP"].isna()]

Empty DataFrame
Columns: [COMP, REGIAO, UF, MUNICIPIO, CNES, NOME ESTABELECIMENTO, RAZAO SOCIAL, TP_GESTAO, CO_TIPO_UNIDADE, DS_TIPO_UNIDADE, NATUREZA_JURIDICA, DESC_NATUREZA_JURIDICA, NO_LOGRADOURO, NU_ENDERECO, NO_COMPLEMENTO, NO_BAIRRO, CO_CEP, NU_TELEFONE, NO_EMAIL, LEITOS EXISTENTE, LEITOS SUS, UTI TOTAL - EXIST, UTI TOTAL - SUS, UTI ADULTO - EXIST, UTI ADULTO - SUS, UTI PEDIATRICO - EXIST, UTI PEDIATRICO - SUS, UTI NEONATAL - EXIST, UTI NEONATAL - SUS, UTI QUEIMADO - EXIST, UTI QUEIMADO - SUS, UTI CORONARIANA - EXIST, UTI CORONARIANA - SUS]
Index: []

[0 rows x 33 columns]

Visto que realmente há uma linha inteira com valores nulos, vamos retira-la através do metodo `dropna()`.

In [73]:
# Deleta as linhas que possuem valores nulos da coluna "COMP"
df_final.dropna(inplace=True, subset=["COMP"])

In [74]:
df_final.isna().sum()

COMP                             0
REGIAO                           0
UF                               0
MUNICIPIO                        0
CNES                             0
NOME ESTABELECIMENTO             0
RAZAO SOCIAL                     0
TP_GESTAO                        0
CO_TIPO_UNIDADE                  0
DS_TIPO_UNIDADE                  0
NATUREZA_JURIDICA                0
DESC_NATUREZA_JURIDICA          47
NO_LOGRADOURO                    0
NU_ENDERECO                    328
NO_COMPLEMENTO             1054770
NO_BAIRRO                        3
CO_CEP                           0
NU_TELEFONE                  77798
NO_EMAIL                    518000
LEITOS EXISTENTE                 0
LEITOS SUS                      53
UTI TOTAL - EXIST                0
UTI TOTAL - SUS                  0
UTI ADULTO - EXIST               0
UTI ADULTO - SUS                 0
UTI PEDIATRICO - EXIST           0
UTI PEDIATRICO - SUS             0
UTI NEONATAL - EXIST             0
UTI NEONATAL - SUS  

Podemos perceber que ela "propagava" a quantidade de nulos para as outras colunas. Agora iremos lidar com os valores nulos das outras colunas

Vamos analisar a coluna "DESC_NATUREZA_JURIDICA" em conjunto com a coluna "NATUREZA_JURIDICA", uma vez que estão correlacionadas. A primeira traz a "descrição" para os valores da segunda.

In [79]:
# DataFrame contendo as linhas (com algumas colunas selecionadas), em que há valores nulos na coluna "DESC_NATUREZA_JURIDICA"
df_final[["CNES","NATUREZA_JURIDICA","DESC_NATUREZA_JURIDICA"]][df_final["DESC_NATUREZA_JURIDICA"].isna()]

CNES  NATUREZA_JURIDICA DESC_NATUREZA_JURIDICA
26026  2318687.0             4014.0                    NaN
26027  2318687.0             4014.0                    NaN
26028  2318687.0             4014.0                    NaN
26029  2318687.0             4014.0                    NaN
26030  2318687.0             4014.0                    NaN
26031  2318687.0             4014.0                    NaN
26032  2318687.0             4014.0                    NaN
30214  2357615.0             4014.0                    NaN
30215  2357615.0             4014.0                    NaN
30216  2357615.0             4014.0                    NaN
30217  2357615.0             4014.0                    NaN
30218  2357615.0             4014.0                    NaN
30219  2357615.0             4014.0                    NaN
30220  2357615.0             4014.0                    NaN
78953  5199123.0             4014.0                    NaN
78954  5199123.0             4014.0                    NaN
78955  5199123.0             4014.0                    NaN
78956  5199123.0             4014.0                    NaN
25491  2318687.0             4014.0                    NaN
25492  2318687.0             4014.0                    NaN
25493  2318687.0             4014.0                    NaN
25494  2318687.0             4014.0                    NaN
25495  2318687.0             4014.0                    NaN
25496  2318687.0             4014.0                    NaN
25497  2318687.0             4014.0                    NaN
25498  2318687.0             4014.0                    NaN
25499  2318687.0             4014.0                    NaN
25500  2318687.0             4014.0                    NaN
25501  2318687.0             4014.0                    NaN
25502  2318687.0             4014.0                    NaN
29654  2357615.0             4014.0                    NaN
29655  2357615.0             4014.0                    NaN
29656  2357615.0             4014.0                    NaN
29657  2357615.0             4014.0                    NaN
25112  2318687.0             4014.0                    NaN
25113  2318687.0             4014.0                    NaN
25114  2318687.0             4014.0                    NaN
25115  2318687.0             4014.0                    NaN
25116  2318687.0             4014.0                    NaN
25117  2318687.0             4014.0                    NaN
25118  2318687.0             4014.0                    NaN
25119  2318687.0             4014.0                    NaN
25120  2318687.0             4014.0                    NaN
25121  2318687.0             4014.0                    NaN
25122  2318687.0             4014.0                    NaN
25123  2318687.0             4014.0                    NaN
24333  2318687.0             4014.0                    NaN

Podemos perceber que todos os valores nulos possuem a "NATUREZA_JUDIRICA" com o valor 4014 associado, então buscaremos nos outros dados se há uma descrição especifica para este valor em questão.

In [92]:
# DataFrame contendo as linhas em que na coluna "NATUREZA_JURIDICA" está preenchida com 4014
df_nj_nulos = df_final[["COMP","CNES","NATUREZA_JURIDICA","DESC_NATUREZA_JURIDICA"]][df_final["NATUREZA_JURIDICA"] == 4014]

# Mostrando o DataFrame
df_nj_nulos

COMP       CNES  NATUREZA_JURIDICA DESC_NATUREZA_JURIDICA
26026  201206.0  2318687.0             4014.0                    NaN
26027  201207.0  2318687.0             4014.0                    NaN
26028  201208.0  2318687.0             4014.0                    NaN
26029  201209.0  2318687.0             4014.0                    NaN
26030  201210.0  2318687.0             4014.0                    NaN
26031  201211.0  2318687.0             4014.0                    NaN
26032  201212.0  2318687.0             4014.0                    NaN
30214  201206.0  2357615.0             4014.0                    NaN
30215  201207.0  2357615.0             4014.0                    NaN
30216  201208.0  2357615.0             4014.0                    NaN
30217  201209.0  2357615.0             4014.0                    NaN
30218  201210.0  2357615.0             4014.0                    NaN
30219  201211.0  2357615.0             4014.0                    NaN
30220  201212.0  2357615.0             4014.0                    NaN
78953  201206.0  5199123.0             4014.0                    NaN
78954  201207.0  5199123.0             4014.0                    NaN
78955  201208.0  5199123.0             4014.0                    NaN
78956  201209.0  5199123.0             4014.0                    NaN
25491  201301.0  2318687.0             4014.0                    NaN
25492  201302.0  2318687.0             4014.0                    NaN
25493  201303.0  2318687.0             4014.0                    NaN
25494  201304.0  2318687.0             4014.0                    NaN
25495  201305.0  2318687.0             4014.0                    NaN
25496  201306.0  2318687.0             4014.0                    NaN
25497  201307.0  2318687.0             4014.0                    NaN
25498  201308.0  2318687.0             4014.0                    NaN
25499  201309.0  2318687.0             4014.0                    NaN
25500  201310.0  2318687.0             4014.0                    NaN
25501  201311.0  2318687.0             4014.0                    NaN
25502  201312.0  2318687.0             4014.0                    NaN
29654  201301.0  2357615.0             4014.0                    NaN
29655  201302.0  2357615.0             4014.0                    NaN
29656  201303.0  2357615.0             4014.0                    NaN
29657  201304.0  2357615.0             4014.0                    NaN
25112  201401.0  2318687.0             4014.0                    NaN
25113  201402.0  2318687.0             4014.0                    NaN
25114  201403.0  2318687.0             4014.0                    NaN
25115  201404.0  2318687.0             4014.0                    NaN
25116  201405.0  2318687.0             4014.0                    NaN
25117  201406.0  2318687.0             4014.0                    NaN
25118  201407.0  2318687.0             4014.0                    NaN
25119  201408.0  2318687.0             4014.0                    NaN
25120  201409.0  2318687.0             4014.0                    NaN
25121  201410.0  2318687.0             4014.0                    NaN
25122  201411.0  2318687.0             4014.0                    NaN
25123  201412.0  2318687.0             4014.0                    NaN
24333  201501.0  2318687.0             4014.0                    NaN

Através dessa busca, por possiveis outros hospitais com o campo "NATUREZA_JURIDICA" igual a 4014. E chegamos aos mesmos valores, então adotaremos outra estratégia: buscar pelos mesmos hosptais que constam nessa lista, através do "CNES" (que é pode ser usado como identificador), em outros periodos para ver se encontramos os valores faltantes.

In [115]:
# DataFrame auxiliar filtrado pelos "CNES" contidos no DataFrame anterior
df_aux = df_final[["CNES","NATUREZA_JURIDICA","DESC_NATUREZA_JURIDICA"]][df_final["CNES"].isin(df_nj_nulos["CNES"])]

# Faz uma contagem sobre a quantidade de linhas para cada "CNES"
df_aux.value_counts("CNES")

CNES
2357615.0    168
2318687.0    145
5199123.0     64
dtype: int64

Analisando, temos 3 "CNES" diferentes que constam esses valores nulos: 2357615, 2318687 e 5199123.

In [118]:
# DataFrame com todos valores do dataset, com a condição de ter um dos CNES descritos anteriormente
#   e agrupados por contagem de valores
df_final[["CNES","DESC_NATUREZA_JURIDICA"]][df_final["CNES"].isin([2357615,2318687,5199123])].value_counts()

CNES       DESC_NATUREZA_JURIDICA
2357615.0  HOSPITAL_PRIVADO          157
2318687.0  HOSPITAL_PRIVADO          113
5199123.0  HOSPITAL_PRIVADO           60
dtype: int64

Observandos valores anteriores, e assumindo que a natureza juridica dessas instituições se mantiveram, preencheremos os valores nulos com o valor de "HOSPITAL_PRIVADO".

In [120]:
# Preenchendo os valores nulos através do metodo .fillna()
df_final["DESC_NATUREZA_JURIDICA"].fillna("HOSPITAL_PRIVADO", inplace=True)

In [121]:
df_final.isna().sum()

COMP                             0
REGIAO                           0
UF                               0
MUNICIPIO                        0
CNES                             0
NOME ESTABELECIMENTO             0
RAZAO SOCIAL                     0
TP_GESTAO                        0
CO_TIPO_UNIDADE                  0
DS_TIPO_UNIDADE                  0
NATUREZA_JURIDICA                0
DESC_NATUREZA_JURIDICA           0
NO_LOGRADOURO                    0
NU_ENDERECO                    328
NO_COMPLEMENTO             1054770
NO_BAIRRO                        3
CO_CEP                           0
NU_TELEFONE                  77798
NO_EMAIL                    518000
LEITOS EXISTENTE                 0
LEITOS SUS                      53
UTI TOTAL - EXIST                0
UTI TOTAL - SUS                  0
UTI ADULTO - EXIST               0
UTI ADULTO - SUS                 0
UTI PEDIATRICO - EXIST           0
UTI PEDIATRICO - SUS             0
UTI NEONATAL - EXIST             0
UTI NEONATAL - SUS  